spring.application.name=alumni-network
server.port=8080

# SQLite Configuration
spring.datasource.url=jdbc:sqlite:alumni.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Hibernate Configuration
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Secret (In production, use a secure, randomly generated secret key)
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expirationMs=86400000
